### ISSUE TITLE
[1.19.2] Crashed, cant get back in

### ISSUE THREAD

**Issue by xanthian** [0xKalKYS/WilderWorld#8]
Game crashed with below error
Cant rejoin the game with mod enabled, disabling mod launches game successfully

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wilderworld'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: me/andante/chord/block/helper/WoodBlocks$Builder
	at me.kaloyankys.wilderworld.init.WWBlocks.<clinit>(WWBlocks.java:57)
	at me.kaloyankys.wilderworld.init.WWBiomeModifications.<clinit>(WWBiomeModifications.java:44)
	at me.kaloyankys.wilderworld.Wilderworld.onInitialize(Wilderworld.java:29)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: me.andante.chord.block.helper.WoodBlocks$Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
```

modlist
```
Loading 159 mods:
	- additionalentityattributes 1.0.0+1.19 via spectrum
	- architectury 6.2.46
	- arclight 0.1.2-1.19.2
	- bclib 2.1.0
	- betterend 2.1.0
	- betternether 7.1.0
	- bewitchment 1.19-5
	- biomemakeover 1.19.2-1.5.12
	- blockus 2.5.2+1.19.2
	- blue_endless_jankson 1.2.1 via owo
	- bwplus 1.19-5
	- cardinal-components-base 5.0.1 via puzzleslib
	- cardinal-components-block 5.0.1 via puzzleslib
	- cardinal-components-chunk 5.0.1 via puzzleslib
	- cardinal-components-entity 5.0.1 via puzzleslib
	- cardinal-components-world 5.0.1 via puzzleslib
	- cinderscapes 3.0.0
	- cinderscapes-client 3.0.0 via cinderscapes
	- cinderscapes-common 3.0.0 via cinderscapes
	- cinderscapes-worldgen 3.0.0 via cinderscapes
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 19 via geckolib3
	- com_eliotlash_molang_molang 19 via geckolib3
	- com_typesafe_config 1.4.1 via croptopia
	- croptopia 2.1.0
	- ecologics 2.1.10
	- enriched 2.4.5
	- enriched-infusions 1.2.1
	- error_notifier 1.0.9 via roughlyenoughitems
	- expert_armor 2.1.6
	- expert_weapons 2.1.0
	- fabric-api 0.62.0+1.19.2
	- fabric-api-base 0.4.12+93d8cb8290 via fabric-api
	- fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.21+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.2+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.35+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.3.1+624e468e90 via fabric-api
	- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
	- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.2.0+b598f4ac90 via fabric-api
	- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
	- fabric-entity-events-v1 1.4.19+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
	- fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
	- fabric-item-groups-v0 0.3.30+93d8cb8290 via fabric-api
	- fabric-key-binding-api-v1 1.0.21+93d8cb8290 via fabric-api
	- fabric-keybindings-v0 0.2.19+df3654b390 via fabric-api
	- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
	- fabric-loot-api-v2 1.1.4+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.7+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.15+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.18+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
	- fabric-networking-v0 0.3.22+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.12+93d8cb8290 via fabric-api
	- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
	- fabric-renderer-api-v1 1.0.11+c6af733c90 via fabric-api
	- fabric-renderer-indigo 0.6.13+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.21+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.15+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
	- fabric-rendering-v0 1.1.23+df3654b390 via fabric-api
	- fabric-rendering-v1 1.11.0+73145abb90 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.12+a29562c890 via fabric-api
	- fabric-resource-loader-v0 0.7.0+93d8cb8290 via fabric-api
	- fabric-screen-api-v1 1.0.27+93d8cb8290 via fabric-api
	- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
	- fabric-textures-v0 1.0.21+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- fiber 0.23.0-2 via patchouli
	- forgeconfigapiport 4.2.6
	- frame 0.26.1+1.19-fabric
	- frame-api-base 0.2.1+906ebc04a9 via frame
	- frame-blocks-v0 0.1.3+233e7428a9 via frame
	- frame-config-v0 0.3.1+0fa45150a9 via frame
	- frame-content-registries-v0 0.4.0+2876b511a9 via frame
	- frame-enchantments-v0 0.1.0+4093105da9 via frame
	- frame-game-rules-v0 0.2.4+e7ce56a6a9 via frame
	- frame-items-v0 0.1.3+906ebc04a9 via frame
	- frame-loot-tables-v0 0.1.4+4f7341eca9 via frame
	- frame-registries-v0 0.1.1+0e0ec74ea9 via frame
	- frame-rendering-v0 0.1.5+906ebc04a9 via frame
	- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9 via frame
	- frame-toymaker-v0 0.6.1+b13741c3a9 via frame
	- frame-woods-v0 0.2.1+6a33fbada9 via frame
	- geckolib3 3.1.20
	- hard-hat-steve 1.1
	- impersonate 2.7.0 via bewitchment
	- incubus_core 1.7 via spectrum
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iris 1.3.1
	- java 17
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- lod 1.6.9a
	- midnightlib 0.5.2 via bewitchment
	- minecraft 1.19.2
	- mm 2.3 via frame-enchantments-v0
	- modmenu 4.0.6
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- owo 0.8.2+1.19
	- patchouli 1.19.2-76-FABRIC
	- pehkui 3.4.2+1.14.4-1.19.2
	- playerabilitylib 1.6.0 via bewitchment
	- programmerartinjector 1.2.1 via spectrum
	- puzzleslib 4.3.8
	- reach-entity-attributes 2.3.0 via arclight
	- reborncore 5.3.4
	- revelationary 1.0.2
	- roughlyenoughitems 9.1.550
	- satin 1.9.0 via spectrum
	- simplemango 1.1.4
	- sodium 0.4.4+build.18
	- spectrum 1.5.5-1.19.2-magic
	- step-height-entity-attribute 1.0.0 via bewitchment
	- team_reborn_energy 2.2.0 via reborncore
	- techreborn 5.3.4
	- terrablender 2.0.1.127
	- terraform-biome-remapper-api-v1 4.1.1 via cinderscapes
	- terraform-config-api-v1 4.1.1 via terrestria
	- terraform-dirt-api-v1 4.1.1 via terrestria
	- terraform-shapes-api-v1 4.1.1 via cinderscapes
	- terraform-surfaces-api-v1 4.1.1 via terrestria
	- terraform-tree-api-v1 4.1.1 via terrestria
	- terraform-wood-api-v1 4.1.1 via bewitchment
	- terrestria 5.0.1
	- terrestria-client 5.0.1 via terrestria
	- terrestria-common 5.0.1 via terrestria
	- terrestria-worldgen 5.0.1 via terrestria
	- traverse 6.0.3
	- traverse-client 6.0.3 via traverse
	- traverse-common 6.0.3 via traverse
	- traverse-worldgen 6.0.3 via traverse
	- trinkets 3.4.0
	- twigs 2.0.0-beta.9+1.19-fabric
	- variant_bookshelves 1.2.0
	- variant_grindstones 1.0.9
	- variant_lanterns 1.0.2
	- variantbarrels 2.2
	- variantcomposters 1.0.4
	- variantcraftingtables 3.2.6
	- wilderworld 2.3.0
```

**Comment by Kirisoup** [comment]
I'm also having the same issue here

**Comment by 0xKY** [comment]
Fixed in the next update
